#!/usr/bin/env bash
set -a

# Initialize fresh workspace dir
[ -d workspace ] && rm -r workspace
mkdir -p workspace

# UCI Env
UCI_WORKSPACE=`pwd`/workspace
UCI_HOOK_SCRIPT=`pwd`/hook
UCI_WATCH_INTERVAL=10

# Source env file, if any
[ -f env ] && source ./env

# Alias uci inside script to project's one
uci() {
 ../uci $@
}

# Single command
uci run echo Hello!

# Bash command
uci run 'echo Init && sleep 1 && echo Done && exit 3'
